### PR TITLE
Code review 

### PR DESCRIPTION
**Pull request by ibr5500**
This is a code review for the portfolio mobile version

### CODE REVIEW

**Comment by ibr5500** [comment]
1 - I need to set a margin for the main text. At lines 34 to 36 the original design has a little bit of extra space on right.
2- In the contact section the items (name & email) are not in the center so I have to delete the text-align: center; for these items, lines 261 & 262 ( classes form-header & form-email)

**Review by Omar-Muhamad — CHANGES_REQUESTED** [review]
# Changes Required ♻️
### Hi @ibr5500 

Nice job, you are almost there.



## (Highlights) Good Points: :+1:
- You documented your work professionally. :heavy_check_mark:
- All linters checks are ok. :heavy_check_mark:

## (Changes Required) Aspects to improve: ♻️

- [ ] You reviewed your portfolio project and you suppose to review project from the past that you completed during the Admissions Trial Please fix that and go back to project [requirments]( https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/review_your_project.md) and apply it.

- [ ] Kindly add at least 2 separate inline comments in your review.

image

- [ ] Please don't talk to yourself (I need ......) but you can ask in frienldy and polite way like (Please add....).

image
image

- [ ] Kindly don't forget to explain why do the project owner need the changes.


## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by ibr5500** [comment]
Ok

**Comment by ibr5500** [comment]
- Please add a right margin for the main-text class at line 34 to give the text right space just similar to the Figma

`.main-text { 
  flex-direction: column; 
  align-items: center; 
  font-weight: 400;
  font-size: 16px;
  line-height: 28px;
  flex: none; 
  order: 1;
  flex-grow: 0;
  margin: 12px 15px 0 0;
  color: #344563;
}`

headline-mobile

- Please delete the text-align: center at lines 405 (form-hear class) and 415 (form-email class) to at the form section because these texts are not in the center as Figma.

`.form-header {
    flex-direction: column;
    color: #172b4d;
    background-color: #fff;
    border-radius: 15px;
    text-align: center;       /*Delete this line*/
    height: 28px;
    padding: 10px 30px;
    flex: none;
    order: 0;
    flex-grow: 0;
    margin-bottom: 10px;
}

.form-email {
    flex-direction: column;
    color: #172b4d;
    background-color: #fff;
    border-radius: 15px;
    text-align: center;       /*Delete this line*/
    height: 28px;
    padding: 10px 30px;
    flex: none;
    order: 1;
    flex-grow: 0;
    margin-bottom: 10px;
}`

**Review by AmaduKamara — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES >♻️

Hi @ibr5500, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
Please try to use inline comments as requested by the previous reviewer and as asked in the project. 

## Suggested changes

- [ ] Please make use of inline comments in reviewing your code. This is about helping you understand how to use GitHub features.
- Please follow these guides on how to go about that. [How to give a code review](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md)
- Please watch this video, it'll help you a lot. [How to perform reviews and make use of GitHub inline comment](https://www.loom.com/share/e847c46aa4814534b23b3a8e4dd60d6d).

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by ibr5500** [comment]
# Changes required ♻️ 

### You are really close 

## 👇  Please check my comments below, and make the requirements changes. 👇 

### Submit when you are done. 

## Thanks 😄

**Review by ibr5500 — COMMENTED** [review]
# Changes required ♻️ 

### You are really close 

## 👇  Please check my comments below, and make the requirements changes. 👇 

### Submit when you are done. 

## Thanks 😄

**Review by phelian23 — CHANGES_REQUESTED** [review]
Hi @ibr5500, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] As requested by the reviewer, Please try to use inline comments. You can learn more on how to do that [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md)
and please watch this video, it'll help you a lot. [How to perform reviews and make use of GitHub inline comment](https://www.loom.com/share/e847c46aa4814534b23b3a8e4dd60d6d).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ibr5500** [comment]
I just did exactly, just like in the video, and I am still getting " Pull request authors cannot request changes on their code ",  could please help?

**Comment by mke2111** [comment]
Project Under Second Opinion Review.
Kindly wait for a response. 😄

**Comment by ibr5500** [comment]
> Hello @ibr5500 👋,
> 
> _This is an additional review as a result of the second opinion request._
> 
> Kindly implement the previously requested changes and then submit your PR for another review. If you need help with the error/issue you were facing, please schedule a 1:1 meeting with any Senior Code Reviewer. Let me know if you need guidance on setting this up.
> 
> Keep rocking 🚀!

Actually, that was my third review request. 
Is there anything I can do for one more review request?

**Pull request merged**
